// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: email_verifications.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredEmailVerifications = `-- name: CleanupExpiredEmailVerifications :exec
DELETE FROM email_verifications
WHERE expires_at < NOW()
`

func (q *Queries) CleanupExpiredEmailVerifications(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredEmailVerifications)
	return err
}

const createEmailVerification = `-- name: CreateEmailVerification :one
INSERT INTO email_verifications (
    id, user_id, token, expires_at
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, token, expires_at, created_at
`

type CreateEmailVerificationParams struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type CreateEmailVerificationRow struct {
	ID        uuid.UUID          `json:"id"`
	Token     string             `json:"token"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (*CreateEmailVerificationRow, error) {
	row := q.db.QueryRow(ctx, createEmailVerification,
		arg.ID,
		arg.UserID,
		arg.Token,
		arg.ExpiresAt,
	)
	var i CreateEmailVerificationRow
	err := row.Scan(
		&i.ID,
		&i.Token,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return &i, err
}

const getEmailVerificationByToken = `-- name: GetEmailVerificationByToken :one
SELECT id, user_id, token, expires_at, used, created_at
FROM email_verifications
WHERE token = $1
  AND used = FALSE
  AND expires_at > NOW()
`

func (q *Queries) GetEmailVerificationByToken(ctx context.Context, token string) (*EmailVerification, error) {
	row := q.db.QueryRow(ctx, getEmailVerificationByToken, token)
	var i EmailVerification
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Token,
		&i.ExpiresAt,
		&i.Used,
		&i.CreatedAt,
	)
	return &i, err
}

const markEmailVerificationUsed = `-- name: MarkEmailVerificationUsed :exec
UPDATE email_verifications
SET used = TRUE
WHERE token = $1
`

func (q *Queries) MarkEmailVerificationUsed(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, markEmailVerificationUsed, token)
	return err
}
