// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CleanupExpiredEmailVerifications(ctx context.Context) error
	CleanupExpiredPasswordResets(ctx context.Context) error
	CleanupExpiredRefreshTokens(ctx context.Context) error
	CreateBackupCodes(ctx context.Context, arg CreateBackupCodesParams) error
	CreateEmailVerification(ctx context.Context, arg CreateEmailVerificationParams) (*CreateEmailVerificationRow, error)
	CreatePasswordReset(ctx context.Context, arg CreatePasswordResetParams) (*CreatePasswordResetRow, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	DeactivateUser(ctx context.Context, id uuid.UUID) error
	DeleteEmailVerificationByUserID(ctx context.Context, userID uuid.UUID) error
	DeletePasswordResetByUserID(ctx context.Context, userID uuid.UUID) error
	DeleteUserBackupCodes(ctx context.Context, userID uuid.UUID) error
	DisableUser2FA(ctx context.Context, id uuid.UUID) error
	EnableUser2FA(ctx context.Context, arg EnableUser2FAParams) error
	GetBackupCodeByHash(ctx context.Context, codeHash string) (*GetBackupCodeByHashRow, error)
	GetEmailVerificationByToken(ctx context.Context, token string) (*EmailVerification, error)
	GetPasswordResetByToken(ctx context.Context, token string) (*PasswordReset, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (*GetRefreshTokenByHashRow, error)
	GetRoleByID(ctx context.Context, id string) (*Role, error)
	GetUnusedBackupCodesForUser(ctx context.Context, userID uuid.UUID) ([]*GetUnusedBackupCodesForUserRow, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	GetUserByEmailOrUsername(ctx context.Context, email string) (*User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (*User, error)
	GetUserByUsername(ctx context.Context, username string) (*User, error)
	ListRoles(ctx context.Context) ([]*Role, error)
	MarkBackupCodeUsed(ctx context.Context, id uuid.UUID) error
	MarkEmailVerificationUsed(ctx context.Context, token string) error
	MarkPasswordResetUsed(ctx context.Context, token string) error
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, id uuid.UUID) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	VerifyUserEmail(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
