// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, role, username, email, password_hash
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, role, username, email, is_active, is_email_verified,
          twofa_secret, twofa_enabled, last_login, created_at, updated_at
`

type CreateUserParams struct {
	ID           uuid.UUID `json:"id"`
	Role         string    `json:"role"`
	Username     string    `json:"username"`
	Email        string    `json:"email"`
	PasswordHash string    `json:"password_hash"`
}

type CreateUserRow struct {
	ID              uuid.UUID          `json:"id"`
	Role            string             `json:"role"`
	Username        string             `json:"username"`
	Email           string             `json:"email"`
	IsActive        bool               `json:"is_active"`
	IsEmailVerified bool               `json:"is_email_verified"`
	TwofaSecret     *string            `json:"twofa_secret"`
	TwofaEnabled    bool               `json:"twofa_enabled"`
	LastLogin       pgtype.Timestamptz `json:"last_login"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Role,
		arg.Username,
		arg.Email,
		arg.PasswordHash,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const deactivateUser = `-- name: DeactivateUser :exec
UPDATE users
SET is_active = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DeactivateUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUser, id)
	return err
}

const disableUser2FA = `-- name: DisableUser2FA :exec
UPDATE users
SET twofa_secret = NULL, twofa_enabled = FALSE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) DisableUser2FA(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, disableUser2FA, id)
	return err
}

const enableUser2FA = `-- name: EnableUser2FA :exec
UPDATE users
SET twofa_secret = $1, twofa_enabled = TRUE, updated_at = NOW()
WHERE id = $2
`

type EnableUser2FAParams struct {
	TwofaSecret *string   `json:"twofa_secret"`
	ID          uuid.UUID `json:"id"`
}

func (q *Queries) EnableUser2FA(ctx context.Context, arg EnableUser2FAParams) error {
	_, err := q.db.Exec(ctx, enableUser2FA, arg.TwofaSecret, arg.ID)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, role, username, email, password_hash, is_active,
       is_email_verified, twofa_secret, twofa_enabled, last_login,
       created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByEmailOrUsername = `-- name: GetUserByEmailOrUsername :one
SELECT
    id,
    role,
    username,
    email,
    password_hash,
    is_active,
    is_email_verified,
    twofa_secret,
    twofa_enabled,
    last_login,
    created_at,
    updated_at
FROM users
WHERE (email = $1 OR username = $1)
  AND is_active = TRUE
`

func (q *Queries) GetUserByEmailOrUsername(ctx context.Context, email string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByEmailOrUsername, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, role, username, email, password_hash, is_active,
       is_email_verified, twofa_secret, twofa_enabled, last_login,
       created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, role, username, email, password_hash, is_active,
       is_email_verified, twofa_secret, twofa_enabled, last_login,
       created_at, updated_at
FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (*User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Role,
		&i.Username,
		&i.Email,
		&i.PasswordHash,
		&i.IsActive,
		&i.IsEmailVerified,
		&i.TwofaSecret,
		&i.TwofaEnabled,
		&i.LastLogin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return &i, err
}

const updateUserLastLogin = `-- name: UpdateUserLastLogin :exec
UPDATE users
SET last_login = NOW()
WHERE id = $1
`

func (q *Queries) UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateUserLastLogin, id)
	return err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $1, updated_at = NOW()
WHERE id = $2
`

type UpdateUserPasswordParams struct {
	PasswordHash string    `json:"password_hash"`
	ID           uuid.UUID `json:"id"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.PasswordHash, arg.ID)
	return err
}

const verifyUserEmail = `-- name: VerifyUserEmail :exec
UPDATE users
SET is_email_verified = TRUE, updated_at = NOW()
WHERE id = $1
`

func (q *Queries) VerifyUserEmail(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, verifyUserEmail, id)
	return err
}
